(function (global) {
  'use strict';

  // Replace these two null values with the website lead conversion values
  // generated by Google Ads. Conversion IDs use the format AW-123456789.
  const config = global.ADAPTIVE_GOOGLE_ADS_CONFIG || {
    conversionId: 'AW-18226072215',
    leadConversionLabel: '6TZxCIXAzeIcEJeV7_JD'
  };

  let initialized = false;
  const convertedResponses = new WeakSet();

  function hasConfiguration() {
    return Boolean(config.conversionId && config.leadConversionLabel);
  }

  function initializeGoogleTag() {
    if (!hasConfiguration() || !global.document) return false;
    if (initialized) return typeof global.gtag === 'function';
    try {
      initialized = true;
      global.dataLayer = global.dataLayer || [];
      global.gtag = global.gtag || function () { global.dataLayer.push(arguments); };

      if (!global.document.querySelector('script[data-adaptive-google-tag]')) {
        const tag = global.document.createElement('script');
        tag.async = true;
        tag.src = 'https://www.googletagmanager.com/gtag/js?id=' + encodeURIComponent(config.conversionId);
        tag.dataset.adaptiveGoogleTag = 'true';
        global.document.head.appendChild(tag);
      }

      global.gtag('js', new Date());
      global.gtag('config', config.conversionId);
      return true;
    } catch (_) {
      return false;
    }
  }

  function recordGoogleAdsLeadConversion() {
    try {
      if (!initializeGoogleTag() || typeof global.gtag !== 'function') return false;
      global.gtag('event', 'conversion', {
        send_to: config.conversionId + '/' + config.leadConversionLabel
      });
      return true;
    } catch (_) {
      // Tracking must never interfere with a successfully submitted lead.
      return false;
    }
  }

  function recordLeadConversionForSubmission(response, result) {
    if (!response || response.ok !== true || !result || result.ok !== true) return false;
    if (convertedResponses.has(response)) return false;
    convertedResponses.add(response);
    return recordGoogleAdsLeadConversion();
  }

  global.AdaptiveGoogleAds = {
    initializeGoogleTag,
    recordLeadConversion: recordLeadConversionForSubmission
  };

  try { initializeGoogleTag(); } catch (_) {}

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { initializeGoogleTag, recordGoogleAdsLeadConversion, recordLeadConversionForSubmission };
  }
}(typeof window !== 'undefined' ? window : globalThis));
